### ISSUE TITLE
Tags are not used

### ISSUE THREAD

**Issue by w33ble** [colynb/generator-go-static#3]
Near as I can tell, the tags on posts don't do anything. Is that still a WIP?

**Comment by collinforrester** [comment]
From what I can tell it seems to be.  I've been thinking of writing some plugin or something that would loop over the pages and create something from them but I'm not sure how to use them yet.

I think it's kind of hard to use tags with a static site?

**Comment by w33ble** [comment]
On my personal blog site, which runs on Docpad, I use tags to query related articles. Tags can also be used as a filter when showing a list of articles. I don't know that they have a lot of utility outside of those 2 examples though.

**Comment by collinforrester** [comment]
I just meant that it's difficult to "query" anything with a static site since there is nothing to query against.  I've written a small snippet of code that will filter by tag(s) that I'll submit a PR for when I'm finished.  And if it takes awhile to merge it, people can just yank it and use it themselves.

**Comment by w33ble** [comment]
Yeah, the "query" part has to happen in the build process, when the static html generation is happening. Docpad uses [query-engine](https://github.com/bevry/query-engine), written by the same author, to do exactly this. I believe go-static is already doing some stuff at build time, it could do more stuff to consume tags

**Comment by colynb** [comment]
precisely... I'm preparing to take the same approach as docpad and other static site generators. That is, anything within the YAML section in a doc should be query-able. For tag pages, you can just create a new document like /src/docs/[TAG].html then just load in the results from a query - then during build that page gets rendered out.

**Comment by w33ble** [comment]
Sounds like a pretty neat way to handle browsing by tag. So long as it can use clean URLs ;)

Looking forward to checking it out.

**Comment by colynb** [comment]
Ok I added tag support... I also added davidgtonge/backbone_query for the query engine. I started using bevry's query-engine but backbone_query seemed simpler to get started with. I'm not that familiar with backbone comparators so it was a little frustrating.

https://github.com/colynb/generator-go-static/wiki/Tags
